# Use a base image with necessary tools
FROM python:3.9-slim

# Set the working directory
WORKDIR /app



# Copy the current directory contents into the container at /app
COPY . .


RUN pip install requests  psycopg2-binary transformers torch


# Use the entrypoint script to start the services
ENTRYPOINT ["python", "bert_classifier.py"]